GET http://localhost:4004/catalog/Books

###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{"ID": 10, "title": "this is my new book: Max Streifeneder"}

###
POST http://localhost:4004/catalog/Orders
Content-Type: application/json

{"ID": "3ae4880c-a34f-4e03-877d-312ccfe03fc5","book_ID": 421, "quantity": 10}